import {esc as e, icon, short, time, relative, labels, badge, empty, button as b, options, safeLink, diffText} from './ui.js';

function timeline(d){
  const entries=[...(d.analyses||[]).map(r=>({at:r.finished_at||r.started_at,title:'Autonomous Mentor · '+r.provider.kind,body:r.result?.rationale||r.error||r.status,refs:[r.id],kind:r.status==='failed'?'failure':'proposal'})),...d.milestones.map(m=>({at:m.created_at,title:'Checkpoint',body:m.summary,refs:m.references})),
    ...d.steps.map(s=>({at:s.recorded_at,title:s.actor+' · '+s.kind,body:s.summary,kind:s.kind,extra:s.rationale,refs:s.snapshot?[s.snapshot]:[]})),
    ...d.notes.map(n=>({at:n.created_at,title:n.actor,body:n.body})),
    ...d.contracts.map(c=>({at:c.created_at,title:'Mentor · '+c.proposed_by,body:c.title,kind:'proposal',contract:c,refs:c.evidence||[]})),
    ...d.executions.map(x=>({at:x.finished_at||x.started_at,title:'Runner · '+(x.actor||x.executor||'External'),body:x.summary||('Execution '+x.status),kind:x.status==='failed'?'failure':'execution',extra:x.rationale,execution:x,refs:[x.output_snapshot||x.input_snapshot]}))].sort((a,b)=>(a.at||0)-(b.at||0));
  return entries.map(x=>`<article class="timeline-item ${e(x.kind||'')}"><i class="timeline-marker"></i><div class="timeline-head"><strong>${e(x.title)}</strong><time>${e(time(x.at))}</time></div><div class="timeline-body">${e(x.body)}</div>${x.execution?executionCard(x.execution):''}${x.contract?proposal(x.contract):x.extra?`<details><summary>Submitted rationale</summary><p class="text-block">${e(x.extra)}</p></details>`:''}${x.refs?.length?`<div class="evidence-row">Evidence · ${x.refs.map(r=>`<code title="${e(r)}">${e(short(r))}</code>`).join(' · ')}</div>`:''}</article>`).join('');
}
function proposal(c){return `<div class="proposal-box">${badge(c.status)}<p class="text-block">${e(c.rationale)}</p><details><summary>Hypothesis, alternatives & completion</summary><dl class="context-list"><dt>Hypothesis</dt><dd>${e(c.hypothesis)}</dd><dt>Alternatives</dt><dd>${e((c.alternatives||[]).join('; ')||'Not submitted')}</dd><dt>Selection</dt><dd>${e(c.selection_reason||c.rationale)}</dd><dt>Write scope</dt><dd class="mono">${e(c.write_scope.join(', '))}</dd><dt>Complete when</dt><dd>${e(c.completion.description)}</dd><dt>Recipe</dt><dd class="mono">${e(c.recipe)} · ${e(short(c.recipe_hash))}</dd></dl></details>${c.last_check?.reasons?.length?`<p class="error-text">Held: ${e(c.last_check.reasons.join(', '))}</p>`:''}<div class="actions">${b('check-contract','Check conditions',c.id)}${b('contract-json','Contract JSON',c.id)}</div></div>`;}
export function session(data,d,tab,apiBase){const state=d.state?.state;return `<section class="session-header"><div class="session-topline">${badge(d.summary.status)}<span class="caption">${e(projectName(data,d.link.project_id))}</span><div class="session-actions">${b('change-reviews','Change reviews')}${b('session-upload','Upload')}${d.review_team?'':b('request-mentor','Request Mentor')}${b('session-settings','Settings')}</div></div><h1>${e(d.session.title)}</h1><p class="session-goal">${e(d.link.goal||d.session.requirements.join('; '))}</p><div class="stat-line"><span>${e(d.session.actors.join(', '))}</span><span>${e(d.session.mode==='suggest'?'Suggestions only':d.session.mode==='execute'?'Delegated execution':'Record only')}</span><span>${e(d.summary.summary)}</span></div></section><div class="detail-grid"><section class="activity-pane"><div class="pane-title"><span>Activity</span><span>Evidence and submitted explanations</span></div>${timeline(d)}<form class="note-form" id="note-form"><label class="sr-only" for="note-body">Add context</label><textarea id="note-body" placeholder="Add context, a decision or a handoff note…" required maxlength="16000"></textarea><footer><span class="caption">Saved to this session</span><button type="submit">Add note ↑</button></footer></form></section><aside class="inspector-pane" aria-label="Session evidence"><div class="inspector-tabs">${['Changes','State','Files','Source'].map(name=>b('inspect',name,name,name===tab?'selected':'')).join('')}</div><div class="inspector-content">${d.states.states.length?`<label class="sr-only" for="state-select">Development state</label><select class="state-select" id="state-select">${d.states.states.map(s=>`<option value="${e(s.id)}" ${s.id===state?.id?'selected':''}>${e(short(s.id))} · ${e(s.summary)}${s.id===d.session.active_state?' (current)':''}</option>`).join('')}</select>`:''}${inspector(d,tab,apiBase)}</div></aside></div>`;}
function inspector(d,tab,apiBase){const v=d.state,s=v?.state;if(tab==='Source')return d.sources?.length?d.sources.map(sourceDetails).join('<hr>'):sourceDetails(d.source);if(!s)return '<p class="empty-inline">No development state captured. Use the API to initialize continuity.</p>';
  if(tab==='Changes')return `<p class="caption">Compared with ${s.parents.length?e(short(s.parents[0])):'an empty baseline (initial import)'}. No automatic CAD merge.</p><div class="section">${v.diffs.map(f=>`<div class="diff-file"><div class="diff-header"><span class="mono">${e(f.path)}</span>${badge(f.kind)}</div>${f.text?diffText(f.text):'<p class="notice">Binary or large file. Download the saved file to inspect.</p>'}</div>`).join('')||'<p class="empty-inline">No file changes in this checkpoint.</p>'}</div>`;
  if(tab==='Files')return `<p class="caption">${Object.keys(v.manifest).length} saved files · ${e(v.storage.replaceAll('_',' '))}</p>${Object.entries(v.manifest).map(([path,f])=>`<div class="file-row">${icon('code')}<div class="name">${e(path)}<div class="caption mono">${e(short(f.hash))} · ${(f.size/1024).toFixed(1)} KB</div></div>${b('download-file','↓',path)}</div>`).join('')}<div class="section"><h3>Restore & continue</h3><p class="caption">Run on your PC. Credentials stay outside the bundle.</p><pre class="restore-command">GANTRY_URL=${e(apiBase)}<br>gantry --token-file ./access.token restore-development-state ${e(s.id)} --destination ./restored-state --key restore-unique-key</pre>${b('download-context','Download context')}</div>`;
  return `<div class="status-axes">${Object.entries(v.status).filter(([k])=>k!=='verification_scope').map(([k,x])=>badge(x,k+': '+x.replaceAll('_',' '))).join('')}</div><div class="section-title"><h2>Robot composition</h2></div><div class="table-wrap"><table class="mini-table"><thead><tr><th>Component</th><th>Version</th><th>Stored</th></tr></thead><tbody>${s.hierarchy.map(n=>`<tr><td>${n.parent?'↳ ':''}${e(n.title)}<div class="caption">${e(n.kind)}</div></td><td class="mono">${e(short(s.components[n.id]?.version))}</td><td>${e(s.components[n.id]?.storage.replaceAll('_',' '))}</td></tr>`).join('')}</tbody></table></div><div class="section"><h3>Parallel changes</h3>${d.states.changes.map(c=>`<div class="file-row"><div class="name">${e(c.title)}<div class="caption">${e(c.assignee)} · ${e(c.write_scope.join(', '))}</div></div>${badge(c.sharing)}</div>`).join('')||'<p class="empty-inline">No parallel change sets.</p>'}</div><div class="section"><h3>Conditions & unknowns</h3><dl class="context-list"><dt>Requirements</dt><dd>${e(s.context.requirements.join('; '))}</dd><dt>Constraints</dt><dd>${e(s.context.constraints.join('; '))}</dd><dt>Unfinished</dt><dd>${e(s.unfinished.join('; ')||'None submitted')}</dd><dt>Not captured</dt><dd>${e(s.capture.missing.join('; ')||'No declared omissions')}</dd><dt>Open questions</dt><dd>${e(s.context.open_questions.join('; ')||'None submitted')}</dd><dt>Decisions</dt><dd>${e(s.context.decisions.join('; ')||'None submitted')}</dd></dl></div><div class="section"><h3>Evaluations</h3>${v.evaluations.map(x=>`<div class="check-row"><span>${e(x.scope)}<div class="caption">${x.applicable?'Applies to this exact state':'Historical; not applicable to this state'}</div></span>${badge(x.applicable?x.verdict:'unverified',x.verdict)}</div>`).join('')||'<p class="empty-inline">No evaluation recorded for this state.</p>'}</div><div class="notice">Sharing, integration and completed execution do not grant formal adoption.</div>${b('adopt-state','Review for adoption',s.id)}`;
}
export function sourceDetails(s){return !s?'<p class="empty-inline">No external source linked to this session.</p>':`<h2>${e(s.title)}</h2><div class="stat-line">${badge(s.kind)}${s.url?safeLink(s.url,'Open source'):''}</div><p class="caption section">${e(s.repository||s.unit||'Unit not identified')} · ${e(s.source_status)}</p><div class="text-block section">${e(s.body)}</div>${s.head_sha?`<div class="notice mono">PR head: ${e(s.head_sha)}<br>Base: ${e(s.base_sha)}</div>`:''}${s.checks?`<div class="section"><h3>CI check runs</h3>${s.checks.map(c=>`<div class="check-row">${e(c.name)}${badge(c.conclusion==='success'?'pass':c.conclusion==='failure'?'fail':'unverified',c.conclusion||c.status)}</div>`).join('')||'<p class="empty-inline">No check runs returned. This is not a passing result.</p>'}</div>`:''}${s.files?.length?`<div class="section"><h3>PR changes</h3>${s.files.map(f=>`<div class="diff-file"><div class="diff-header">${e(f.filename)} <span>+${e(f.additions)} −${e(f.deletions)}</span></div>${f.patch?diffText(f.patch):'<p class="notice">Patch not available</p>'}</div>`).join('')}</div>`:''}${Object.keys(s.observed_configuration||{}).length?`<div class="section"><h3>Observed configuration</h3><pre class="restore-command">${e(JSON.stringify(s.observed_configuration,null,2))}</pre></div>`:''}<div class="notice">Not captured: ${e((s.capture_missing||[]).join('; ')||'No declared omissions')}. Source text is evidence, not execution authorization.</div>`;}
const projectName=(data,id)=>data.projects.find(p=>p.id===id)?.name||'Unassigned project';
const heading=(title,description,actions='')=>`<div class="page-heading"><div><h1>${e(title)}</h1><p class="muted">${e(description)}</p></div><div class="actions">${actions}</div></div>`;
export function sidebar(data,route){
  const nav=[['sessions','Sessions'],['inbox','Incoming'],['automation','Automation'],['projects','Projects'],['integrations','Integrations']];
  return {nav:nav.map(([id,label])=>`<a href="#${id}" class="${route===id?'active':''}">${icon(id)}${label}<span class="nav-count">${id==='sessions'?data.sessions.length:id==='inbox'?data.signals.length:''}</span></a>`).join(''),
    projects:data.projects.map(p=>`<a class="project-nav" href="#project/${e(p.id)}"><span class="project-icon">${e(p.name.slice(0,2).toUpperCase())}</span>${e(p.name)}</a>`).join('')||'<div class="caption empty-inline">No projects yet</div>',
    recent:[...data.sessions].sort((a,b)=>b.created_at-a.created_at).slice(0,8).map(s=>`<a class="recent-link" href="#session/${e(s.id)}"><strong>${e(s.title)}</strong><span class="caption"><i class="dot ${e(s.status)}"></i>${e(labels[s.status])} · ${e(relative(s.created_at))}</span></a>`).join('')};
}
export function sessions(data,filter){
  const selected=data.sessions.filter(s=>(!filter.project||s.project_id===filter.project)&&(!filter.status||s.status===filter.status)&&`${s.title} ${projectName(data,s.project_id)} ${s.actors.join(' ')}`.toLowerCase().includes(filter.query.toLowerCase()));
  const card=s=>`<a class="session-card" href="#session/${e(s.id)}"><div class="card-project">${e(projectName(data,s.project_id))}</div><div class="card-title">${e(s.title)}</div><div class="card-bottom"><i class="dot ${e(s.status)}"></i>${e(s.actors[0]||s.owner)}<span>${e(relative(s.created_at))}</span></div>${s.automation_project?'<div class="caption">Started by Automation</div>':''}<div class="card-detail">${e(s.summary)}</div></a>`;
  const board=`<div class="board">${Object.entries(labels).map(([key,label])=>`<section class="board-column"><h2 class="column-head">${icon(key)}${label}<span class="count">${selected.filter(s=>s.status===key).length}</span></h2>${selected.filter(s=>s.status===key).map(card).join('')||'<div class="column-empty">No sessions</div>'}</section>`).join('')}</div>`;
  const list=`<div class="table-wrap"><table><thead><tr><th>Session</th><th>Project</th><th>Status</th><th>Assigned</th><th>Started</th></tr></thead><tbody>${selected.map(s=>`<tr><td><a href="#session/${e(s.id)}">${e(s.title)}</a><div class="caption">${e(s.summary)}</div></td><td>${e(projectName(data,s.project_id))}</td><td>${badge(s.status)}</td><td>${e(s.actors.join(', '))}</td><td>${e(relative(s.created_at))}</td></tr>`).join('')}</tbody></table></div>`;
  return `<div class="page">${heading('Sessions','Follow improvement work across hardware and software.',b('new-session','New session','','primary'))}<div class="toolbar"><div class="segmented" aria-label="Session layout">${b('board','Board','',filter.layout==='board'?'selected':'')}${b('list','List','',filter.layout==='list'?'selected':'')}</div><div class="filters"><select id="project-filter" aria-label="Filter by project"><option value="">All projects</option>${options(data.projects,'id','name',filter.project)}</select><select id="status-filter" aria-label="Filter by status"><option value="">All statuses</option>${options(Object.entries(labels).map(([id,name])=>({id,name})),'id','name',filter.status)}</select></div><input id="session-search" type="search" placeholder="Search sessions…" aria-label="Search sessions" value="${e(filter.query)}"></div>${data.sessions.length?(selected.length?(filter.layout==='board'?board:list):empty('No matching sessions','Try a different search or filter.')):empty('Start with one improvement','Connect a repository or upload a project, then start a session.',b('new-project','Create project'))}</div>`;
}
export function inbox(data){return `<div class="page">${heading('Incoming','Issues, pull requests and operational observations from connected services.',b('connect','Connect a service'))}${data.signals.length?`<div class="table-wrap"><table><thead><tr><th>Source</th><th>Title</th><th>Project</th><th>Automation</th><th>Updated</th><th></th></tr></thead><tbody>${[...data.signals].sort((a,b)=>b.received_at-a.received_at).map(s=>`<tr><td>${badge(s.kind)}<div class="caption">${e(s.source_status)}</div></td><td><button data-action="source" data-id="${e(s.id)}">${e(s.title)}</button><div class="caption">${e(s.repository||s.unit||'Unit not specified')}${s.number?' #'+e(s.number):''}</div></td><td>${e(projectName(data,s.project_id))}</td><td>${s.assessment&&s.assessment.revision_id===s.revision_id?`${badge(s.assessment.action)}<div class="caption">${e(s.assessment.rationale)}</div>${s.assessment.session_id?`<a href="#session/${e(s.assessment.session_id)}">Open session →</a>`:''}`:'Not assessed'}</td><td>${e(relative(s.received_at))}</td><td>${b('from-source','Start session',s.id)}</td></tr>`).join('')}</tbody></table></div>`:empty('No incoming signals','Connect GitHub and synchronize, or send observations through the monitoring API.',b('connect','Connect a service'))}</div>`;}
export function projects(data){return `<div class="page">${heading('Projects','Keep robot configurations, evidence and improvement work together.',b('new-project','New project','','primary'))}<div class="project-grid">${data.projects.map(p=>`<a class="project-card" href="#project/${e(p.id)}"><h2>${e(p.name)}</h2><p>${e(p.description)}</p><div class="stat-line"><span>${data.sessions.filter(s=>s.project_id===p.id).length} sessions</span><span>${data.integrations.filter(i=>i.project_id===p.id&&i.enabled).length} connections</span></div><div class="caption section">${p.baseline_state?'Baseline '+e(short(p.baseline_state)):'Baseline not selected'}</div></a>`).join('')}</div>${!data.projects.length?empty('Bring an existing robot project','Import the state you have. Missing history and unverified behavior stay explicit.',b('new-project','Create project')):''}</div>`;}
export function project(data,detail){const p=detail.project;return `<div class="page">${heading(p.name,p.description,b('edit-project','Edit',p.id)+b('upload','Upload files',p.id,'primary'))}<div class="notice">${p.baseline_state?'Shared baseline: '+e(short(p.baseline_state)):'No shared baseline selected. Upload a saved bundle and start a session first.'} ${b('baseline','Set baseline',p.id)}</div><div class="section-title"><h2>Improvement sessions</h2>${b('new-session','New session',p.id)}</div>${data.sessions.filter(s=>s.project_id===p.id).map(s=>`<div class="integration-row"><div class="integration-info"><a href="#session/${e(s.id)}">${e(s.title)}</a><div class="caption">${e(s.summary)}</div></div>${badge(s.status)}</div>`).join('')||'<p class="empty-inline">No sessions linked yet.</p>'}<div class="section"><div class="section-title"><h2>Saved files</h2><span class="caption">Uploads do not change the approved configuration</span></div>${detail.uploads.length?`<div class="table-wrap"><table><thead><tr><th>Bundle</th><th>Type</th><th>Files</th><th>Saved</th><th></th></tr></thead><tbody>${[...detail.uploads].reverse().map(u=>`<tr><td>${e(u.summary)}<div class="caption mono">${e(short(u.snapshot))}</div></td><td>${e(u.category)}</td><td>${u.file_count} · ${(u.bytes/1024).toFixed(1)} KB</td><td>${e(time(u.created_at))}</td><td>${b('upload-files','Browse',u.id)}</td></tr>`).join('')}</tbody></table></div>`:empty('No uploaded files','Upload editable CAD, electrical design, code, models or operational logs.',b('upload','Upload files',p.id))}</div><div class="section"><h2>Connections</h2>${data.integrations.filter(i=>i.project_id===p.id).map(i=>`<div class="integration-row"><div class="integration-info">${e(i.name)}<div class="caption">${e(i.repository||'Authenticated monitoring API')}</div></div>${badge(i.status)}</div>`).join('')||'<p class="empty-inline">No services connected.</p>'}</div></div>`;}
export function integrations(data){return `<div class="page">${heading('Integrations','Connect your development tools and operational data.',b('connect','Add connection','','primary'))}<h2>Connected services</h2><p class="caption">Connections are scoped to a project. Source data is treated as evidence.</p><div class="section integration-list">${data.integrations.map(i=>`<div class="integration-row"><span class="service-icon">${i.provider==='github'?icon('github'):'API'}</span><div class="integration-info"><strong>${e(i.name)}</strong><div class="caption">${e(projectName(data,i.project_id))} · ${e(i.repository||'Monitoring intake')}</div><span class="inline-status ${e(i.status)}">${e(i.status.replaceAll('_',' '))}</span><span class="caption"> · ${i.last_sync?'Last received '+e(relative(i.last_sync)):'No data received yet'}</span>${i.last_error?`<div class="error-text">${e(i.last_error.message)}</div>`:''}${i.partial?'<div class="caption">Partial history; additional records remain at the source.</div>':''}</div><div class="integration-actions">${i.enabled&&i.provider==='github'?b('sync','Sync now',i.id):''}${b('integration-config','Configure',i.id)}</div></div>`).join('')||'<p class="empty-inline integration-row">No services configured yet.</p>'}</div><div class="section"><h2>Available connections</h2><div class="integration-list section"><div class="integration-row"><span class="service-icon">${icon('github')}</span><div class="integration-info"><strong>GitHub</strong><div class="caption">Issues, pull requests, changed files and CI check runs. Read-only.</div></div>${b('connect-github','Connect')}</div><div class="integration-row"><span class="service-icon">API</span><div class="integration-info"><strong>Monitoring API</strong><div class="caption">Operational incidents, actual configurations, measurements and log references.</div></div>${b('connect-monitoring','Configure')}</div><div class="integration-row"><span class="service-icon">↥</span><div class="integration-info"><strong>CAD, electrical design & simulation</strong><div class="caption">Saved files via upload or a local adapter. Native CAD editor integration is not connected.</div></div>${b('adapter-help','Setup')}</div></div></div><div class="section"><div class="section-title"><h2>Mentor & local runners</h2>${b('worker-help','Connect a worker')}</div><div class="integration-list">${data.workers.map(w=>`<div class="integration-row"><span class="service-icon">${w.kind==='mentor'?'M':'R'}</span><div class="integration-info"><strong>${e(w.worker_id)}</strong><div class="caption">${e(w.actor)} · ${e(w.summary)} · ${e(relative(w.last_seen))}</div></div>${badge(w.online?'connected':'attention',w.online?w.status:'Offline')}</div>`).join('')||'<p class="integration-row caption">No worker has reported a heartbeat. Automatic proposals and execution need a configured worker.</p>'}</div></div></div>`;}

function executionCard(x){return `<div class="proposal-box">${badge(x.status==='failed'?'fail':x.status,x.status)} <span class="caption">Exit ${e(x.exit_code??'pending')} · ${e(x.engineering_verdict||'not evaluated')}</span>${x.reasons?.length?`<p class="error-text">${e(x.reasons.join('; '))}</p>`:''}<div class="actions">${b('execution-json','Execution record',x.id)}${x.logs_snapshot?b('execution-logs','Saved logs',x.id):''}</div></div>`;}

export function automation(data, status){
  const money=n=>'$'+(n/1000000).toFixed(4);
  return `<div class="page">${heading('Automation','Incoming → evidence-based decisions → delegated work. Hardware and software share the same development state.')}
    <p class="notice">Inference, execution and formal adoption are separate. Fixture runs test the workflow; they are not production model analysis.</p>
    ${status.projects.map(item=>{const p=item.project,policy=item.policy;
      const workers=data.workers.filter(w=>w.kind==='analyst'&&w.project_ids?.includes(p.id)&&w.online);
      return `<section class="section automation-project"><div class="section-title"><div><h2>${e(p.name)}</h2><p class="caption">${policy?e(policy.provider.kind+' / '+policy.provider.model):'Not configured'} · ${workers.length?workers.length+' analyst(s) online':'No analyst online'}</p></div><div class="actions">${badge(policy?.enabled?'connected':'unverified',policy?.enabled?'Enabled':'Paused')}${data.permissions.human?b('automation-config','Configure',p.id):''}${policy?.enabled&&data.permissions.human?b('automation-pause','Pause',p.id):''}</div></div>
      ${workers.map(w=>`<p class="caption">${e(w.worker_id)} · ${e(w.summary)}</p>`).join('')}
      <div class="stat-line"><span>${item.pending_signals} unassessed signals</span><span>${item.usage.daily_calls} / ${policy?.max_daily_calls??'—'} analyses today</span><span>${money(item.usage.monthly_microusd)} / ${policy?money(policy.max_monthly_microusd):'—'} this UTC month</span><span>${policy?.enabled&&policy?.session_template.mode==='execute'?'Bounded execution enabled':'Execution disabled / suggestions only'}</span></div>
      ${policy?.provider.kind==='fixture'?'<p class="notice">Test fixture. No paid model connected.</p>':''}
      ${policy?.provider.kind==='external'?'<p class="notice">External analyst via leased API. Model launch is managed outside Gantry; subscription usage is not metered here.</p>':''}
      <div class="table-wrap section"><table><thead><tr><th>Analysis</th><th>Status</th><th>Decision / reason</th><th>Usage</th><th>Time</th></tr></thead><tbody>${item.runs.map(r=>`<tr><td>${e(r.kind)}<div class="caption">${e(r.actor)} · ${e(r.worker_id)}</div></td><td>${badge(r.status)}${r.status==='running'&&r.lease_until<status.now?'<div class="caption">Lease expired; awaiting reconciliation</div>':''}</td><td>${e(r.error||r.result?.rationale||r.result?.action||'')}${r.result?.decisions?.map(c=>`<div>${badge(c.disposition)} ${e(c.title)}<div class="caption">${e(c.rationale)}</div>${c.session_id?`<a href="#session/${e(c.session_id)}">Open session →</a>`:''}</div>`).join('')||''}${r.session_id?`<div><a href="#session/${e(r.session_id)}">Open session →</a></div>`:''}<div>${b('analysis-record','Record',r.id)}</div></td><td>${r.usage?e(r.usage.input_tokens+' in / '+r.usage.output_tokens+' out'):'Usage unknown'}<div class="caption">${money(r.charged_microusd??r.reserved_microusd)} · ${e(r.usage_status)}</div></td><td>${e(time(r.started_at))}</td></tr>`).join('')||'<tr><td colspan="5">No analysis yet. Configure a provider, delegation and an analyst worker.</td></tr>'}</tbody></table></div></section>`;
    }).join('')||empty('Create a project first','Automation is scoped to a project and a saved development baseline.')}</div>`;
}
